# Generated by Django 4.1.5 on 2023-08-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guideapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phone1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone2',
            field=models.IntegerField(),
        ),
    ]
